# Generated by Django 5.2.7 on 2026-08-27 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(default='LKR', help_text='Primary currency ISO code (e.g. LKR, USD, EUR, GBP, INR)', max_length=10),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='LKR', help_text='Preferred primary currency code (e.g. LKR, USD, EUR, GBP, INR)', max_length=10)),
                ('currency_symbol', models.CharField(default='Rs.', help_text='Display symbol for preferred currency', max_length=10)),
                ('default_currency', models.CharField(default='LKR', help_text='Default currency for transactions and budgets', max_length=10)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD (e.g. 2026-08-27)'), ('DD/MM/YYYY', 'DD/MM/YYYY (e.g. 27/08/2026)'), ('MM/DD/YYYY', 'MM/DD/YYYY (e.g. 08/27/2026)')], default='YYYY-MM-DD', help_text='Preferred date display format', max_length=20)),
                ('timezone', models.CharField(default='UTC', help_text='User local timezone e.g. UTC, Asia/Colombo, America/New_York', max_length=50)),
                ('language', models.CharField(default='en', help_text='Preferred display language code', max_length=10)),
                ('financial_year_start_month', models.PositiveSmallIntegerField(default=1, help_text='Month when financial year begins (1=Jan to 12=Dec)')),
                ('default_transaction_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', help_text='Default transaction type selected when creating entries', max_length=10)),
                ('budget_alerts', models.BooleanField(default=True, help_text='Receive notifications when budgets reach warning or exceeded thresholds')),
                ('goal_alerts', models.BooleanField(default=True, help_text='Receive notifications for financial goal progress and milestones')),
                ('recurring_transaction_alerts', models.BooleanField(default=True, help_text='Receive notifications for upcoming due or generated recurring transactions')),
                ('system_notifications', models.BooleanField(default=True, help_text='Receive general system and security notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', help_text='User display or screen name', max_length=100)),
                ('bio', models.TextField(blank=True, default='', help_text='Short bio or user description')),
                ('phone_number', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
