# Generated by Django 5.2.7 on 2026-08-18 03:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_run_date', models.DateField()),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='transactions.recurringtransaction'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('recurring_transaction', 'recurring_schedule_date'), name='unique_recurring_occurrence'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active', 'next_run_date'], name='idx_rec_user_act_next'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'category'], name='idx_rec_user_category'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'transaction_type'], name='idx_rec_user_type'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'frequency'], name='idx_rec_user_freq'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='recurring_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='recurring_start_lte_end_date'),
        ),
    ]
