# Generated by Django 5.2.7 on 2026-08-20 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_financialgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BUDGET_EXCEEDED', 'Budget Exceeded'), ('BUDGET_WARNING', 'Budget Warning'), ('GOAL_COMPLETED', 'Goal Completed'), ('GOAL_WARNING', 'Goal Warning'), ('RECURRING_DUE', 'Recurring Transaction Due'), ('RECURRING_GENERATED', 'Recurring Transaction Generated'), ('RECURRING_EXPIRED', 'Recurring Schedule Expired')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='idx_notif_user_is_read'), models.Index(fields=['user', 'notification_type'], name='idx_notif_user_type'), models.Index(fields=['user', 'created_at'], name='idx_notif_user_created')],
            },
        ),
    ]
