# Generated by Django 5.2.7 on 2026-08-29 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_DOWNLOADED', 'Backup Downloaded'), ('BACKUP_DELETED', 'Backup Deleted'), ('RESTORE_VALIDATED', 'Restore Validated')], max_length=30),
        ),
        migrations.CreateModel(
            name='DataBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full Backup'), ('TRANSACTIONS', 'Transactions & Categories'), ('SELECTED_DATA', 'Selected Data')], default='FULL', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/%Y/%m/')),
                ('file_size', models.BigIntegerField(default=0, help_text='Backup file size in bytes')),
                ('record_count', models.IntegerField(default=0, help_text='Total number of records included in backup')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Detailed section record counts and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Backup',
                'verbose_name_plural': 'Data Backups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_backup_user_created'), models.Index(fields=['user', 'status'], name='idx_backup_user_status'), models.Index(fields=['expires_at'], name='idx_backup_expires_at')],
            },
        ),
    ]
