# Generated by Django 5.2.7 on 2026-08-31 06:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_auditlog_action_databackup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransactionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Recurring Transaction Execution',
                'verbose_name_plural': 'Recurring Transaction Executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='interval',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_DOWNLOADED', 'Backup Downloaded'), ('BACKUP_DELETED', 'Backup Deleted'), ('RESTORE_VALIDATED', 'Restore Validated'), ('RECURRING_TRANSACTION_CREATED', 'Recurring Transaction Created'), ('RECURRING_TRANSACTION_UPDATED', 'Recurring Transaction Updated'), ('RECURRING_TRANSACTION_PAUSED', 'Recurring Transaction Paused'), ('RECURRING_TRANSACTION_RESUMED', 'Recurring Transaction Resumed'), ('RECURRING_TRANSACTION_EXECUTED', 'Recurring Transaction Executed'), ('RECURRING_TRANSACTION_DELETED', 'Recurring Transaction Deleted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BUDGET_EXCEEDED', 'Budget Exceeded'), ('BUDGET_WARNING', 'Budget Warning'), ('GOAL_COMPLETED', 'Goal Completed'), ('GOAL_WARNING', 'Goal Warning'), ('RECURRING_DUE', 'Recurring Transaction Due'), ('RECURRING_GENERATED', 'Recurring Transaction Generated'), ('RECURRING_EXPIRED', 'Recurring Schedule Expired'), ('RECURRING_TRANSACTION_CREATED', 'Recurring Transaction Created'), ('RECURRING_TRANSACTION_EXECUTED', 'Recurring Transaction Executed'), ('RECURRING_TRANSACTION_FAILED', 'Recurring Transaction Failed'), ('RECURRING_TRANSACTION_PAUSED', 'Recurring Transaction Paused'), ('RECURRING_TRANSACTION_RESUMED', 'Recurring Transaction Resumed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('interval__gt', 0)), name='recurring_interval_positive'),
        ),
        migrations.AddField(
            model_name='recurringtransactionexecution',
            name='recurring_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_history', to='transactions.recurringtransaction'),
        ),
        migrations.AddField(
            model_name='recurringtransactionexecution',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='recurringtransactionexecution',
            index=models.Index(fields=['recurring_transaction', '-executed_at'], name='idx_rec_exec_tx_time'),
        ),
        migrations.AddIndex(
            model_name='recurringtransactionexecution',
            index=models.Index(fields=['status'], name='idx_rec_exec_status'),
        ),
    ]
