# Generated by Django 5.2.7 on 2026-09-01 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_recurringtransactionexecution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_DOWNLOADED', 'Backup Downloaded'), ('BACKUP_DELETED', 'Backup Deleted'), ('RESTORE_VALIDATED', 'Restore Validated'), ('RECURRING_TRANSACTION_CREATED', 'Recurring Transaction Created'), ('RECURRING_TRANSACTION_UPDATED', 'Recurring Transaction Updated'), ('RECURRING_TRANSACTION_PAUSED', 'Recurring Transaction Paused'), ('RECURRING_TRANSACTION_RESUMED', 'Recurring Transaction Resumed'), ('RECURRING_TRANSACTION_EXECUTED', 'Recurring Transaction Executed'), ('RECURRING_TRANSACTION_DELETED', 'Recurring Transaction Deleted'), ('DATA_IMPORT_CREATED', 'Data Import Created'), ('DATA_IMPORT_PREVIEWED', 'Data Import Previewed'), ('DATA_IMPORT_EXECUTED', 'Data Import Executed'), ('DATA_IMPORT_FAILED', 'Data Import Failed'), ('DATA_IMPORT_DELETED', 'Data Import Deleted')], max_length=30),
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PREVIEW_READY', 'Preview Ready'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('duplicate_rows', models.IntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('preview_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Import',
                'verbose_name_plural': 'Data Imports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_import_user_created'), models.Index(fields=['user', 'status'], name='idx_import_user_status')],
            },
        ),
    ]
