# Generated by Django 5.2.7 on 2026-09-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_auditlog_action_dataimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_DOWNLOADED', 'Backup Downloaded'), ('BACKUP_DELETED', 'Backup Deleted'), ('RESTORE_VALIDATED', 'Restore Validated'), ('RECURRING_TRANSACTION_CREATED', 'Recurring Transaction Created'), ('RECURRING_TRANSACTION_UPDATED', 'Recurring Transaction Updated'), ('RECURRING_TRANSACTION_PAUSED', 'Recurring Transaction Paused'), ('RECURRING_TRANSACTION_RESUMED', 'Recurring Transaction Resumed'), ('RECURRING_TRANSACTION_EXECUTED', 'Recurring Transaction Executed'), ('RECURRING_TRANSACTION_DELETED', 'Recurring Transaction Deleted'), ('DATA_IMPORT_CREATED', 'Data Import Created'), ('DATA_IMPORT_PREVIEWED', 'Data Import Previewed'), ('DATA_IMPORT_EXECUTED', 'Data Import Executed'), ('DATA_IMPORT_FAILED', 'Data Import Failed'), ('DATA_IMPORT_DELETED', 'Data Import Deleted'), ('DATA_EXPORT_CREATED', 'Data Export Created'), ('DATA_EXPORT_COMPLETED', 'Data Export Completed'), ('DATA_EXPORT_DOWNLOADED', 'Data Export Downloaded'), ('DATA_EXPORT_DELETED', 'Data Export Deleted'), ('DATA_EXPORT_FAILED', 'Data Export Failed')], max_length=30),
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('export_type', models.CharField(choices=[('TRANSACTIONS', 'Transactions'), ('CATEGORIES', 'Categories'), ('BUDGETS', 'Budgets'), ('GOALS', 'Goals'), ('RECURRING_TRANSACTIONS', 'Recurring Transactions'), ('FULL_FINANCIAL_DATA', 'Full Financial Data')], default='FULL_FINANCIAL_DATA', max_length=50)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON')], default='JSON', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('record_count', models.IntegerField(default=0)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export',
                'verbose_name_plural': 'Data Exports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_export_user_created'), models.Index(fields=['user', 'status'], name='idx_export_user_status'), models.Index(fields=['expires_at'], name='idx_export_expires_at')],
            },
        ),
    ]
