# Generated by Django 5.2.7 on 2026-09-04 04:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_auditlog_action_dataexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='goal_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('EMERGENCY_FUND', 'Emergency Fund'), ('PURCHASE', 'Purchase'), ('TRAVEL', 'Travel'), ('INVESTMENT', 'Investment'), ('DEBT_REPAYMENT', 'Debt Repayment'), ('OTHER', 'Other')], default='SAVINGS', max_length=30),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['user', 'status'], name='idx_goal_user_status'),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['user', 'goal_type'], name='idx_goal_user_goal_type'),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['user', 'priority'], name='idx_goal_user_priority'),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['user', 'created_at'], name='idx_goal_user_created'),
        ),
        migrations.AddConstraint(
            model_name='financialgoal',
            constraint=models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='goal_current_amount_non_negative'),
        ),
    ]

