# Generated by Django 5.2.7 on 2026-09-04 04:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_goalcontribution_financialgoal_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.TextField(blank=True, default='')),
                ('contribution_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='transactions.financialgoal')),
            ],
            options={
                'verbose_name': 'Goal Contribution',
                'verbose_name_plural': 'Goal Contributions',
                'ordering': ['-contribution_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['goal', '-contribution_date'], name='idx_contrib_goal_date'),
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['goal', '-created_at'], name='idx_contrib_goal_created'),
        ),
        migrations.AddConstraint(
            model_name='goalcontribution',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='contribution_amount_positive'),
        ),
    ]
